{{- if .Values.taigaAsyncRabbitmq.persistence.enabled }}
{{- $rabbitmq := .Values.taigaAsyncRabbitmq.persistence -}}
{{- if (not $rabbitmq.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "taiga.fullname" . }}-async-rabbitmq-data
  annotations:
  {{- range $key, $value := $rabbitmq.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if eq .Values.taigaAsyncRabbitmq.persistence.resourcePolicy "keep" }}
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
  {{ include "taiga.labels" . | indent 4 }}
    component: async-rabbitmq-persistent
spec:
  accessModes:
  - {{ .Values.taigaAsyncRabbitmq.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.taigaAsyncRabbitmq.persistence.size }}
  {{- if $rabbitmq.storageClass }}
    {{- if eq "-" $rabbitmq.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ $rabbitmq.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}